[package]
name = "chess2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
termion = "1.5"
log4rs = "1.1.1"
tinyrand = "0.5.0"